spring:
  application:
    name: ServerSide

  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/day0322_bd_pro?serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 8080

# Mybatis自动映射
mybatis:
  configuration:
    auto-mapping-behavior: full
  # 别名映射:统一访问包名
  type-aliases-package: com.cc.ccserverside.pojo
  # mapper.xml位置
  mapper-locations: classpath:mappers/*.xml

# Mybatis日志
logging:
  level:
    com.cc.ccserverside.dao: debug


